<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yuberley Cruz Caycedo">
<meta name="dcterms.date" content="2025-08-23">

<title>Metodología Box-Jenkins para Modelos ARIMA – Yuberley Cruz Caycedo | Portafolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Yuberley Cruz Caycedo | Portafolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">Sobre Mí</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../proyectos.html"> 
<span class="menu-text">Proyectos</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/yuberley20"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/tu-usuario/"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introducción-el-modelo-arima" id="toc-introducción-el-modelo-arima" class="nav-link active" data-scroll-target="#introducción-el-modelo-arima"><span class="header-section-number">1</span> Introducción: El Modelo ARIMA</a></li>
  <li><a href="#familiarizarse-con-la-serie" id="toc-familiarizarse-con-la-serie" class="nav-link" data-scroll-target="#familiarizarse-con-la-serie"><span class="header-section-number">2</span> Familiarizarse con la Serie</a>
  <ul class="collapse">
  <li><a href="#carga-y-preparación-de-los-datos" id="toc-carga-y-preparación-de-los-datos" class="nav-link" data-scroll-target="#carga-y-preparación-de-los-datos"><span class="header-section-number">2.1</span> Carga y Preparación de los Datos</a></li>
  <li><a href="#análisis-gráfico-inicial" id="toc-análisis-gráfico-inicial" class="nav-link" data-scroll-target="#análisis-gráfico-inicial"><span class="header-section-number">2.2</span> Análisis Gráfico Inicial</a></li>
  </ul></li>
  <li><a href="#análisis-de-estacionariedad" id="toc-análisis-de-estacionariedad" class="nav-link" data-scroll-target="#análisis-de-estacionariedad"><span class="header-section-number">3</span> Análisis de Estacionariedad</a>
  <ul class="collapse">
  <li><a href="#análisis-de-correlogramas-acf-y-pacf" id="toc-análisis-de-correlogramas-acf-y-pacf" class="nav-link" data-scroll-target="#análisis-de-correlogramas-acf-y-pacf"><span class="header-section-number">3.1</span> Análisis de Correlogramas (ACF y PACF)</a></li>
  <li><a href="#pruebas-estadísticas-formales" id="toc-pruebas-estadísticas-formales" class="nav-link" data-scroll-target="#pruebas-estadísticas-formales"><span class="header-section-number">3.2</span> Pruebas Estadísticas Formales</a></li>
  <li><a href="#transformaciones-para-alcanzar-la-estacionariedad" id="toc-transformaciones-para-alcanzar-la-estacionariedad" class="nav-link" data-scroll-target="#transformaciones-para-alcanzar-la-estacionariedad"><span class="header-section-number">3.3</span> Transformaciones para alcanzar la Estacionariedad</a></li>
  </ul></li>
  <li><a href="#identificar-el-proceso-generador-de-datos-pgd" id="toc-identificar-el-proceso-generador-de-datos-pgd" class="nav-link" data-scroll-target="#identificar-el-proceso-generador-de-datos-pgd"><span class="header-section-number">4</span> Identificar el Proceso Generador de Datos (PGD)</a>
  <ul class="collapse">
  <li><a href="#interpretación-de-los-correlogramas" id="toc-interpretación-de-los-correlogramas" class="nav-link" data-scroll-target="#interpretación-de-los-correlogramas"><span class="header-section-number">4.1</span> Interpretación de los Correlogramas</a></li>
  <li><a href="#modelos-candidatos" id="toc-modelos-candidatos" class="nav-link" data-scroll-target="#modelos-candidatos"><span class="header-section-number">4.2</span> Modelos Candidatos</a></li>
  </ul></li>
  <li><a href="#especificación-y-estimación-del-modelo" id="toc-especificación-y-estimación-del-modelo" class="nav-link" data-scroll-target="#especificación-y-estimación-del-modelo"><span class="header-section-number">5</span> Especificación y Estimación del Modelo</a>
  <ul class="collapse">
  <li><a href="#estimación-de-modelos-candidatos" id="toc-estimación-de-modelos-candidatos" class="nav-link" data-scroll-target="#estimación-de-modelos-candidatos"><span class="header-section-number">5.1</span> Estimación de Modelos Candidatos</a></li>
  <li><a href="#comparación-de-modelos" id="toc-comparación-de-modelos" class="nav-link" data-scroll-target="#comparación-de-modelos"><span class="header-section-number">5.2</span> Comparación de Modelos</a></li>
  <li><a href="#selección-del-mejor-modelo" id="toc-selección-del-mejor-modelo" class="nav-link" data-scroll-target="#selección-del-mejor-modelo"><span class="header-section-number">5.3</span> Selección del Mejor Modelo</a></li>
  </ul></li>
  <li><a href="#validación-del-modelo-seleccionado" id="toc-validación-del-modelo-seleccionado" class="nav-link" data-scroll-target="#validación-del-modelo-seleccionado"><span class="header-section-number">6</span> Validación del Modelo Seleccionado</a>
  <ul class="collapse">
  <li><a href="#análisis-gráfico-de-los-residuales" id="toc-análisis-gráfico-de-los-residuales" class="nav-link" data-scroll-target="#análisis-gráfico-de-los-residuales"><span class="header-section-number">6.1</span> Análisis Gráfico de los Residuales</a></li>
  <li><a href="#pruebas-formales-sobre-los-residuales" id="toc-pruebas-formales-sobre-los-residuales" class="nav-link" data-scroll-target="#pruebas-formales-sobre-los-residuales"><span class="header-section-number">6.2</span> Pruebas Formales sobre los Residuales</a></li>
  <li><a href="#conclusión-de-la-validación" id="toc-conclusión-de-la-validación" class="nav-link" data-scroll-target="#conclusión-de-la-validación"><span class="header-section-number">6.3</span> Conclusión de la Validación</a></li>
  </ul></li>
  <li><a href="#realizar-el-pronóstico" id="toc-realizar-el-pronóstico" class="nav-link" data-scroll-target="#realizar-el-pronóstico"><span class="header-section-number">7</span> Realizar el Pronóstico</a>
  <ul class="collapse">
  <li><a href="#generación-del-pronóstico" id="toc-generación-del-pronóstico" class="nav-link" data-scroll-target="#generación-del-pronóstico"><span class="header-section-number">7.1</span> Generación del Pronóstico</a></li>
  <li><a href="#visualización-del-pronóstico" id="toc-visualización-del-pronóstico" class="nav-link" data-scroll-target="#visualización-del-pronóstico"><span class="header-section-number">7.2</span> Visualización del Pronóstico</a></li>
  </ul></li>
  <li><a href="#validación-de-la-predicción" id="toc-validación-de-la-predicción" class="nav-link" data-scroll-target="#validación-de-la-predicción"><span class="header-section-number">8</span> Validación de la Predicción</a>
  <ul class="collapse">
  <li><a href="#preparación-de-los-datos-para-validación" id="toc-preparación-de-los-datos-para-validación" class="nav-link" data-scroll-target="#preparación-de-los-datos-para-validación"><span class="header-section-number">8.1</span> Preparación de los Datos para Validación</a></li>
  <li><a href="#re-estimación-y-pronóstico-fuera-de-muestra" id="toc-re-estimación-y-pronóstico-fuera-de-muestra" class="nav-link" data-scroll-target="#re-estimación-y-pronóstico-fuera-de-muestra"><span class="header-section-number">8.2</span> Re-estimación y Pronóstico Fuera de Muestra</a></li>
  <li><a href="#cálculo-de-las-métricas-de-precisión" id="toc-cálculo-de-las-métricas-de-precisión" class="nav-link" data-scroll-target="#cálculo-de-las-métricas-de-precisión"><span class="header-section-number">8.3</span> Cálculo de las Métricas de Precisión</a></li>
  <li><a href="#conclusión-de-la-validación-1" id="toc-conclusión-de-la-validación-1" class="nav-link" data-scroll-target="#conclusión-de-la-validación-1"><span class="header-section-number">8.4</span> Conclusión de la Validación</a></li>
  </ul></li>
  <li><a href="#utilización-de-los-resultados-para-la-toma-de-decisiones" id="toc-utilización-de-los-resultados-para-la-toma-de-decisiones" class="nav-link" data-scroll-target="#utilización-de-los-resultados-para-la-toma-de-decisiones"><span class="header-section-number">9</span> Utilización de los Resultados para la Toma de Decisiones</a>
  <ul class="collapse">
  <li><a href="#aplicaciones-prácticas-del-pronóstico-del-pib" id="toc-aplicaciones-prácticas-del-pronóstico-del-pib" class="nav-link" data-scroll-target="#aplicaciones-prácticas-del-pronóstico-del-pib"><span class="header-section-number">9.1</span> Aplicaciones Prácticas del Pronóstico del PIB</a></li>
  <li><a href="#limitaciones-y-consideraciones" id="toc-limitaciones-y-consideraciones" class="nav-link" data-scroll-target="#limitaciones-y-consideraciones"><span class="header-section-number">9.2</span> Limitaciones y Consideraciones</a></li>
  </ul></li>
  <li><a href="#conclusión-general-del-taller" id="toc-conclusión-general-del-taller" class="nav-link" data-scroll-target="#conclusión-general-del-taller"><span class="header-section-number">10</span> Conclusión General del Taller</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias"><span class="header-section-number">11</span> Referencias</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Metodología Box-Jenkins para Modelos ARIMA</h1>
<p class="subtitle lead">Análisis del PIB de Argentina</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yuberley Cruz Caycedo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 23, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introducción-el-modelo-arima" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introducción-el-modelo-arima"><span class="header-section-number">1</span> Introducción: El Modelo ARIMA</h2>
<p>Un modelo ARIMA es un tipo de modelo estadístico utilizado para analizar y predecir series temporales. Este modelo combina componentes de Autorregresión (AR), Integración (I) y Media Móvil (MA) para capturar las estructuras y patrones presentes en los datos temporales.</p>
<blockquote class="blockquote">
<p>Definición de ARIMA (Box-Jenkins): “Los modelos ARIMA son una clase de modelos que pueden representar series de tiempo estacionarias y no estacionarias. Un modelo ARIMA es una modificación de un modelo ARMA que permite que la serie subyacente sea no estacionaria. La letra ‘I’ en ARIMA significa ‘integrado’, lo cual es una referencia a la operación de diferenciación.”</p>
<p>— Pindyck, R. S., &amp; Rubinfeld, D. L. (2001). Econometría: Modelos y Pronósticos (4a ed.).</p>
</blockquote>
<p>La forma general de un modelo ARIMA(p,d,q) se puede expresar como:</p>
<p><span class="math display">\[(1 - \sum_{i=1}^{p} \phi_i L^i)(1-L)^d Y_t = c + (1 + \sum_{j=1}^{q} \theta_j L^j)\epsilon_t\]</span></p>
<p>Donde:</p>
<ul>
<li><p><span class="math inline">\(Y_t\)</span> es el valor observado en el tiempo t.</p></li>
<li><p><span class="math inline">\(p\)</span> es el orden del componente autorregresivo (AR).</p></li>
<li><p><span class="math inline">\(d\)</span> es el número de diferencias necesarias para alcanzar la estacionariedad.</p></li>
<li><p><span class="math inline">\(q\)</span> es el orden del componente de media móvil (MA).</p></li>
<li><p><span class="math inline">\(\phi_i\)</span> son los parámetros autorregivos.</p></li>
<li><p><span class="math inline">\(\theta_j\)</span> son los parámetros de media móvil.</p></li>
<li><p><span class="math inline">\(\epsilon_t\)</span> es un término de error de ruido blanco, <span class="math inline">\(\epsilon_t \sim iid N(0, \sigma^2_\epsilon)\)</span>.</p></li>
</ul>
<p>A continuación, se enumeran los pasos de la metodología Box-Jenkins para la construcción de un modelo ARIMA.</p>
<hr>
</section>
<section id="familiarizarse-con-la-serie" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="familiarizarse-con-la-serie"><span class="header-section-number">2</span> Familiarizarse con la Serie</h2>
<p>Antes de cualquier análisis técnico, es crucial entender el contexto de los datos. En este caso, analizaremos la serie anual del Producto Interno Bruto (PIB) de Argentina.</p>
<section id="carga-y-preparación-de-los-datos" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="carga-y-preparación-de-los-datos"><span class="header-section-number">2.1</span> Carga y Preparación de los Datos</h3>
<p>En lugar de cargar un archivo externo, definimos los datos directamente en el documento para asegurar la reproducibilidad del análisis.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un tibble (data frame) con los datos del PIB de Argentina</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pib_argentina_raw <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Periodo =</span> <span class="dv">1960</span><span class="sc">:</span><span class="dv">2021</span>, <span class="co"># El rango de años es hasta 2021 para coincidir con los 62 puntos de datos.</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">PIB Argentina</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">150797810295.884</span>, <span class="fl">158982878499.524</span>, <span class="fl">157628310158.567</span>, <span class="fl">149261089202.812</span>, </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">164381681831.918</span>, <span class="fl">181755894112.433</span>, <span class="fl">180556802912.311</span>, <span class="fl">186320169964.576</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">195305461613.156</span>, <span class="fl">214210104570.482</span>, <span class="fl">220734180309.322</span>, <span class="fl">233223609573.669</span>, </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">237021461356.448</span>, <span class="fl">243685921868.226</span>, <span class="fl">257171024124.452</span>, <span class="fl">257097956426.363</span>, </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">251909073021.038</span>, <span class="fl">269376023758.644</span>, <span class="fl">260383783021.038</span>, <span class="fl">279583538643.552</span>, </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">282476135644.759</span>, <span class="fl">263436798302.104</span>, <span class="fl">260952386435.524</span>, <span class="fl">269047613564.476</span>, </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">275644759426.363</span>, <span class="fl">260952386435.524</span>, <span class="fl">278631151978.962</span>, <span class="fl">286311519789.623</span>, </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">285023864355.241</span>, <span class="fl">267390476135.645</span>, <span class="fl">264388480210.377</span>, <span class="fl">277341803093.223</span>, </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">304263625611.519</span>, <span class="fl">316374388480.21</span>, <span class="fl">333201697896.226</span>, <span class="fl">321500475942.636</span>, </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">339047613564.476</span>, <span class="fl">365611519789.623</span>, <span class="fl">379523864355.241</span>, <span class="fl">365285386435.524</span>, </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">362561151978.962</span>, <span class="fl">353260952386.436</span>, <span class="fl">383418030932.226</span>, <span class="fl">419523864355.241</span>, </span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">461047613564.476</span>, <span class="fl">503418030932.226</span>, <span class="fl">548302103773.904</span>, <span class="fl">594263625611.519</span>, </span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">632103773904.761</span>, <span class="fl">601523864355.241</span>, <span class="fl">659047613564.476</span>, <span class="fl">658302103773.904</span>, </span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">643884802103.774</span>, <span class="fl">657390476135.645</span>, <span class="fl">642561151978.962</span>, <span class="fl">657047613564.476</span>, </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">640952386435.524</span>, <span class="fl">625285386435.524</span>, <span class="fl">592636256115.198</span>, <span class="fl">578302103773.904</span>, </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">641302103773.904</span>, <span class="fl">622047613564.476</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir los datos a un objeto de serie de tiempo (ts)</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>pib_ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(pib_argentina_raw<span class="sc">$</span><span class="st">`</span><span class="at">PIB Argentina</span><span class="st">`</span>, </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>             <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1960</span>, <span class="dv">1</span>), </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>             <span class="at">frequency =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="análisis-gráfico-inicial" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="análisis-gráfico-inicial"><span class="header-section-number">2.2</span> Análisis Gráfico Inicial</h3>
<p>Graficamos la serie para observar su comportamiento a lo largo del tiempo.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar la serie de tiempo</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(pib_ts, </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"PIB de Argentina (1960-2021)"</span>, <span class="co"># Título del gráfico</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"PIB (en unidades monetarias)"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"#0072B2"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Metodología-Box-Jenkins-para-Modelos-ARIMA_files/figure-html/plot-series-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>PIB de Argentina (1960-2021).</figcaption>
</figure>
</div>
</div>
</div>
<p>Observación Inicial: El gráfico muestra una clara tendencia ascendente a lo largo del tiempo, con algunas fluctuaciones. Una serie con una tendencia tan marcada es un indicio visual de que no es estacionaria.</p>
<hr>
</section>
</section>
<section id="análisis-de-estacionariedad" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="análisis-de-estacionariedad"><span class="header-section-number">3</span> Análisis de Estacionariedad</h2>
<p>Este es el primer paso técnico fundamental. Debemos verificar formalmente si la serie es estacionaria.</p>
<section id="análisis-de-correlogramas-acf-y-pacf" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="análisis-de-correlogramas-acf-y-pacf"><span class="header-section-number">3.1</span> Análisis de Correlogramas (ACF y PACF)</h3>
<p>La forma de la Función de Autocorrelación (ACF) nos da una pista clave sobre la estacionariedad.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar la Función de Autocorrelación (ACF) y Parcial (PACF)</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf2</span>(pib_ts, <span class="at">main =</span> <span class="st">"ACF y PACF del PIB de Argentina (Niveles)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Metodología-Box-Jenkins-para-Modelos-ARIMA_files/figure-html/plot-acf-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>ACF y PACF para la serie del PIB en niveles.</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]  [,2] [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9] [,10] [,11] [,12]
ACF  0.96  0.91 0.87  0.82  0.77  0.71  0.65  0.59  0.53  0.47  0.40  0.34
PACF 0.96 -0.09 0.04 -0.13 -0.08 -0.10 -0.07 -0.01 -0.05  0.02 -0.11  0.02
     [,13] [,14] [,15] [,16] [,17] [,18]
ACF   0.29  0.23  0.18  0.13  0.09  0.06
PACF  0.03 -0.11  0.05  0.00  0.04  0.03</code></pre>
</div>
</div>
<p>Interpretación del ACF: La Función de Autocorrelación (la gráfica superior) decae muy lentamente. Los rezagos se mantienen altos y positivos por un largo tiempo. Esta es una característica clásica de una serie no estacionaria.</p>
</section>
<section id="pruebas-estadísticas-formales" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="pruebas-estadísticas-formales"><span class="header-section-number">3.2</span> Pruebas Estadísticas Formales</h3>
<section id="prueba-de-ruido-blanco-ljung-box" class="level4" data-number="3.2.1">
<h4 data-number="3.2.1" class="anchored" data-anchor-id="prueba-de-ruido-blanco-ljung-box"><span class="header-section-number">3.2.1</span> Prueba de Ruido Blanco (Ljung-Box)</h4>
<p>Esta prueba nos confirma si la serie tiene alguna estructura o es completamente aleatoria.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: La serie es ruido blanco.</li>
</ul>
<!-- -->
<ul>
<li><span class="math inline">\(H_A\)</span>: La serie no es ruido blanco.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar la prueba de Ljung-Box para los primeros 10 rezagos</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(pib_ts, <span class="at">lag =</span> <span class="dv">10</span>, <span class="at">type =</span> <span class="st">"Ljung-Box"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  pib_ts
X-squared = 382.97, df = 10, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Resultado: El <code>p-value</code> es extremadamente pequeño (<code>&lt; 2.2e-16</code>), por lo que rechazamos la hipótesis nula. Esto confirma que la serie no es ruido blanco y tiene una estructura que podemos modelar.</p>
</section>
<section id="prueba-de-raíz-unitaria-dickey-fuller-aumentada" class="level4" data-number="3.2.2">
<h4 data-number="3.2.2" class="anchored" data-anchor-id="prueba-de-raíz-unitaria-dickey-fuller-aumentada"><span class="header-section-number">3.2.2</span> Prueba de Raíz Unitaria (Dickey-Fuller Aumentada)</h4>
<p>Esta es la prueba formal de estacionariedad.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: La serie tiene una raíz unitaria (es no estacionaria).</li>
</ul>
<!-- -->
<ul>
<li><span class="math inline">\(H_A\)</span>: La serie no tiene raíz unitaria (es estacionaria).</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar la prueba de Dickey-Fuller Aumentada</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Usamos el tipo "trend" porque la serie visualmente tiene una tendencia</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>adf_test_result <span class="ot">&lt;-</span> <span class="fu">ur.df</span>(pib_ts, <span class="at">type =</span> <span class="st">"trend"</span>, <span class="at">selectlags =</span> <span class="st">"AIC"</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(adf_test_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression trend 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + tt + z.diff.lag)

Residuals:
       Min         1Q     Median         3Q        Max 
-3.680e+10 -1.356e+10 -6.829e+08  1.273e+10  5.926e+10 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)  1.123e+10  6.773e+09   1.659    0.103
z.lag.1     -7.303e-02  4.526e-02  -1.613    0.112
tt           7.016e+08  4.283e+08   1.638    0.107
z.diff.lag   1.347e-01  1.338e-01   1.006    0.319

Residual standard error: 2.074e+10 on 56 degrees of freedom
Multiple R-squared:  0.05723,   Adjusted R-squared:  0.006727 
F-statistic: 1.133 on 3 and 56 DF,  p-value: 0.3436


Value of test-statistic is: -1.6134 2.7885 1.3705 

Critical values for test statistics: 
      1pct  5pct 10pct
tau3 -4.04 -3.45 -3.15
phi2  6.50  4.88  4.16
phi3  8.73  6.49  5.47</code></pre>
</div>
</div>
<p>Interpretación del Test DFA: Para determinar si rechazamos la hipótesis nula (no estacionariedad), comparamos el estadístico de prueba (<code>Value of test-statistic</code>) con los valores críticos (<code>critical values</code>).</p>
<ul>
<li><p>Estadístico de prueba (tau3): -1.61</p></li>
<li><p>Valor crítico al 5%: -3.45</p></li>
</ul>
<p>Como el valor absoluto del estadístico de prueba (1.61) es menor que el valor absoluto del valor crítico al 5% (3.45), no podemos rechazar la hipótesis nula.</p>
<p>Conclusión: Tanto el análisis gráfico como las pruebas formales confirman que la serie del PIB de Argentina es no estacionaria.</p>
</section>
</section>
<section id="transformaciones-para-alcanzar-la-estacionariedad" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="transformaciones-para-alcanzar-la-estacionariedad"><span class="header-section-number">3.3</span> Transformaciones para alcanzar la Estacionariedad</h3>
<p>Para continuar con el modelado, necesitamos transformar la serie. El primer paso es aplicar una primera diferencia.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la primera diferencia de la serie</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>pib_diff1 <span class="ot">&lt;-</span> <span class="fu">diff</span>(pib_ts)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar la serie diferenciada</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(pib_diff1, </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Primera Diferencia del PIB de Argentina"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Cambio en el PIB"</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"#D55E00"</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Metodología-Box-Jenkins-para-Modelos-ARIMA_files/figure-html/difference-series-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Primera diferencia del PIB de Argentina.</figcaption>
</figure>
</div>
</div>
</div>
<p>Observación: La serie diferenciada parece fluctuar alrededor de una media constante (cercana a cero), lo que sugiere que podría ser estacionaria. Vamos a verificarlo formalmente.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar el test DFA a la serie diferenciada</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>adf_test_diff_result <span class="ot">&lt;-</span> <span class="fu">ur.df</span>(pib_diff1, <span class="at">type =</span> <span class="st">"drift"</span>, <span class="at">selectlags =</span> <span class="st">"AIC"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(adf_test_diff_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)

Residuals:
       Min         1Q     Median         3Q        Max 
-4.705e+10 -1.433e+10  2.958e+08  1.113e+10  6.334e+10 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  6.053e+09  3.060e+09   1.978   0.0528 .  
z.lag.1     -7.593e-01  1.795e-01  -4.231 8.72e-05 ***
z.diff.lag  -1.607e-01  1.445e-01  -1.112   0.2710    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.098e+10 on 56 degrees of freedom
Multiple R-squared:  0.4521,    Adjusted R-squared:  0.4326 
F-statistic: 23.11 on 2 and 56 DF,  p-value: 4.815e-08


Value of test-statistic is: -4.2306 8.9523 

Critical values for test statistics: 
      1pct  5pct 10pct
tau2 -3.51 -2.89 -2.58
phi1  6.70  4.71  3.86</code></pre>
</div>
</div>
<p>Interpretación del Test DFA en la serie diferenciada:</p>
<ul>
<li>Estadístico de prueba (tau2): -4.23</li>
<li>Valor crítico al 5%: -2.89</li>
</ul>
<p>Ahora, el valor absoluto del estadístico de prueba (4.23) es mayor que el valor absoluto del valor crítico al 5% (2.89). Por lo tanto, rechazamos la hipótesis nula.</p>
<p>Conclusión Final: La primera diferencia de la serie del PIB de Argentina es estacionaria. Esto significa que nuestra serie original es integrada de orden 1, o I(1). En nuestro modelo ARIMA(p,d,q), ya hemos encontrado el valor de d = 1.</p>
<hr>
</section>
</section>
<section id="identificar-el-proceso-generador-de-datos-pgd" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="identificar-el-proceso-generador-de-datos-pgd"><span class="header-section-number">4</span> Identificar el Proceso Generador de Datos (PGD)</h2>
<p>Una vez que tenemos una serie estacionaria (<code>pib_diff1</code>), analizamos sus correlogramas (ACF y PACF) para proponer los órdenes p (AR) y q (MA) del modelo.</p>
<blockquote class="blockquote">
<p>Identificación del Modelo: “La principal herramienta para llevar a cabo la identificación del modelo es el correlograma, una gráfica de las funciones de autocorrelación y de autocorrelación parcial de la serie… La ACF y la PACF de un proceso ARMA(p,q) tienen características distintivas que a menudo pueden revelar los órdenes p y q.”</p>
<p>— Pindyck, R. S., &amp; Rubinfeld, D. L. (2001). Econometría: Modelos y Pronósticos (4a ed.).</p>
</blockquote>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar la ACF y PACF de la serie estacionaria (diferenciada)</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf2</span>(pib_diff1, <span class="at">main =</span> <span class="st">"ACF y PACF del PIB de Argentina (Primera Diferencia)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Metodología-Box-Jenkins-para-Modelos-ARIMA_files/figure-html/plot-acf-diff-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>ACF y PACF para la serie del PIB diferenciada.</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3]  [,4] [,5]  [,6]  [,7]  [,8]  [,9] [,10] [,11] [,12] [,13]
ACF   0.1 0.15 0.15  0.04 0.15 -0.09 -0.05 -0.14 -0.10  0.11 -0.29 -0.04 -0.03
PACF  0.1 0.14 0.13 -0.01 0.12 -0.14 -0.07 -0.15 -0.04  0.16 -0.25  0.01  0.03
     [,14] [,15] [,16] [,17] [,18]
ACF  -0.02 -0.10 -0.07 -0.02  0.03
PACF  0.04 -0.18  0.03 -0.03  0.09</code></pre>
</div>
</div>
<section id="interpretación-de-los-correlogramas" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="interpretación-de-los-correlogramas"><span class="header-section-number">4.1</span> Interpretación de los Correlogramas</h3>
<p>Observamos los gráficos de ACF y PACF para la serie <code>pib_diff1</code>:</p>
<ul>
<li><p>ACF (Función de Autocorrelación Simple): La gráfica superior muestra un rezago significativo en <code>k=1</code> que está justo en el límite de la banda de confianza. Los demás rezagos no parecen ser significativos. Este comportamiento de corte abrupto después del primer rezago es característico de un proceso MA(1).</p></li>
<li><p>PACF (Función de Autocorrelación Parcial): La gráfica inferior también muestra un rezago significativo en <code>k=1</code> que sobresale claramente, mientras que los siguientes decaen rápidamente. Este patrón de corte después del primer rezago es característico de un proceso AR(1).</p></li>
</ul>
</section>
<section id="modelos-candidatos" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="modelos-candidatos"><span class="header-section-number">4.2</span> Modelos Candidatos</h3>
<p>Dado que tanto la ACF como la PACF muestran un comportamiento similar (un rezago significativo y luego un decaimiento), es difícil decidirse por un modelo puro AR o MA. Por lo tanto, propondremos varios modelos candidatos simples para evaluarlos en el siguiente paso:</p>
<ol type="1">
<li><p>ARIMA(1,1,0): Un modelo autorregresivo de orden 1 para la serie diferenciada.</p></li>
<li><p>ARIMA(0,1,1): Un modelo de media móvil de orden 1 para la serie diferenciada.</p></li>
<li><p>ARIMA(1,1,1): Un modelo mixto que incluye tanto un término AR como uno MA.</p></li>
<li><p>ARIMA(0,1,0): Un modelo de caminata aleatoria con deriva, como punto de referencia simple.</p></li>
</ol>
<hr>
</section>
</section>
<section id="especificación-y-estimación-del-modelo" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="especificación-y-estimación-del-modelo"><span class="header-section-number">5</span> Especificación y Estimación del Modelo</h2>
<p>En esta etapa, estimamos los modelos candidatos que propusimos y los comparamos utilizando un criterio de selección de información para encontrar el más adecuado.</p>
<blockquote class="blockquote">
<p>Selección del Modelo: “En la práctica, la selección del ‘mejor’ modelo ARIMA es a menudo un arte. Uno de los criterios más utilizados para la selección de modelos es el Criterio de Información de Akaike (AIC). El AIC penaliza la adición de parámetros extra y, por lo tanto, nos anima a elegir modelos parsimoniosos.”</p>
<p>— Gujarati, D. N., &amp; Porter, D. C. (2009). Econometría (5a ed.).</p>
</blockquote>
<section id="estimación-de-modelos-candidatos" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="estimación-de-modelos-candidatos"><span class="header-section-number">5.1</span> Estimación de Modelos Candidatos</h3>
<p>Utilizamos la función <code>Arima</code> del paquete <code>forecast</code>, que estima los parámetros por el método de Máxima Verosimilitud.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimar los cuatro modelos candidatos</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Usamos la serie original (pib_ts), la función Arima se encarga de la diferenciación (d=1)</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>modelo_110 <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">Arima</span>(pib_ts, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>modelo_011 <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">Arima</span>(pib_ts, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>modelo_111 <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">Arima</span>(pib_ts, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>modelo_010 <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">Arima</span>(pib_ts, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="comparación-de-modelos" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="comparación-de-modelos"><span class="header-section-number">5.2</span> Comparación de Modelos</h3>
<p>Creamos una tabla para comparar los valores de AIC y BIC (Criterio de Información Bayesiano) de cada modelo. El mejor modelo será aquel con los valores más bajos.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una tabla de resumen con los criterios de información</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>resumen_modelos <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Modelo =</span> <span class="fu">c</span>(<span class="st">"ARIMA(1,1,0)"</span>, <span class="st">"ARIMA(0,1,1)"</span>, <span class="st">"ARIMA(1,1,1)"</span>, <span class="st">"ARIMA(0,1,0)"</span>),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC =</span> <span class="fu">c</span>(<span class="fu">AIC</span>(modelo_110), <span class="fu">AIC</span>(modelo_011), <span class="fu">AIC</span>(modelo_111), <span class="fu">AIC</span>(modelo_010)),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">BIC =</span> <span class="fu">c</span>(<span class="fu">BIC</span>(modelo_110), <span class="fu">BIC</span>(modelo_011), <span class="fu">BIC</span>(modelo_111), <span class="fu">BIC</span>(modelo_010))</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar la tabla ordenada por el AIC (de menor a mayor)</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>resumen_modelos <span class="sc">%&gt;%</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(AIC) <span class="sc">%&gt;%</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Comparación de Criterios de Información para Modelos Candidatos"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Comparación de Criterios de Información para Modelos Candidatos</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Modelo</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ARIMA(1,1,1)</td>
<td style="text-align: right;">3076.212</td>
<td style="text-align: right;">3082.545</td>
</tr>
<tr class="even">
<td style="text-align: left;">ARIMA(1,1,0)</td>
<td style="text-align: right;">3078.731</td>
<td style="text-align: right;">3082.953</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ARIMA(0,1,1)</td>
<td style="text-align: right;">3079.551</td>
<td style="text-align: right;">3083.773</td>
</tr>
<tr class="even">
<td style="text-align: left;">ARIMA(0,1,0)</td>
<td style="text-align: right;">3079.768</td>
<td style="text-align: right;">3081.879</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="selección-del-mejor-modelo" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="selección-del-mejor-modelo"><span class="header-section-number">5.3</span> Selección del Mejor Modelo</h3>
<p>Interpretación: Al observar la tabla, el modelo ARIMA(0,1,0) presenta el valor de AIC y BIC más bajo de todos los modelos candidatos. Este modelo es también conocido como una caminata aleatoria con deriva (random walk with drift).</p>
<p>Aunque los correlogramas sugerían una estructura AR(1) o MA(1), los criterios de información indican que el modelo más simple es el que mejor se ajusta a los datos, una vez penalizado por su complejidad.</p>
<p>Por lo tanto, seleccionamos el ARIMA(0,1,0) como nuestro modelo final para proceder a la validación.</p>
<hr>
</section>
</section>
<section id="validación-del-modelo-seleccionado" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="validación-del-modelo-seleccionado"><span class="header-section-number">6</span> Validación del Modelo Seleccionado</h2>
<p>Una vez que hemos seleccionado un modelo, debemos realizar un diagnóstico para asegurarnos de que es adecuado. Este paso es crucial para garantizar la fiabilidad de nuestros futuros pronósticos.</p>
<blockquote class="blockquote">
<p>Verificación de Diagnóstico: “La verificación de diagnóstico es un paso en el cual se examinan los residuos de un modelo ajustado para comprobar si son de ruido blanco. Si no lo son, el modelo debe ser reespecificado… Si los residuos son de ruido blanco, el modelo se considera adecuado.”</p>
<p>— Gujarati, D. N., &amp; Porter, D. C. (2009). Econometría (5a ed.).</p>
</blockquote>
<p>La principal herramienta para la validación es el análisis de los residuos. Si el modelo es bueno, los residuos no deberían tener ninguna estructura predecible; deberían ser indistinguibles de un proceso de ruido blanco.</p>
<section id="análisis-gráfico-de-los-residuales" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="análisis-gráfico-de-los-residuales"><span class="header-section-number">6.1</span> Análisis Gráfico de los Residuales</h3>
<p>La función <code>checkresiduals()</code> del paquete <code>forecast</code> es una excelente herramienta que nos proporciona un resumen visual y una prueba formal.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar el análisis de diagnóstico de los residuos</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">checkresiduals</span>(best_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Metodología-Box-Jenkins-para-Modelos-ARIMA_files/figure-html/check-residuals-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Gráficos de diagnóstico para los residuos del modelo ARIMA(0,1,0).</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(0,1,0)
Q* = 9.1454, df = 10, p-value = 0.5184

Model df: 0.   Total lags used: 10</code></pre>
</div>
</div>
<p>Interpretación de los Gráficos:</p>
<ol type="1">
<li>Gráfico de Residuos a lo largo del Tiempo (arriba): Los residuos parecen fluctuar aleatoriamente alrededor de cero, sin ninguna tendencia o patrón obvio. Esto es una buena señal.</li>
<li>ACF de los Residuos (abajo a la izquierda): Ninguna de las autocorrelaciones (las barras verticales) excede significativamente las bandas de confianza azules. Esto sugiere que no hay autocorrelación remanente en los residuos.</li>
<li>Histograma de los Residuos (abajo a la derecha): La distribución de los residuos se asemeja a una distribución normal (la curva superpuesta), lo cual es deseable.</li>
</ol>
</section>
<section id="pruebas-formales-sobre-los-residuales" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="pruebas-formales-sobre-los-residuales"><span class="header-section-number">6.2</span> Pruebas Formales sobre los Residuales</h3>
<section id="prueba-de-no-autocorrelación-ljung-box" class="level4" data-number="6.2.1">
<h4 data-number="6.2.1" class="anchored" data-anchor-id="prueba-de-no-autocorrelación-ljung-box"><span class="header-section-number">6.2.1</span> Prueba de No Autocorrelación (Ljung-Box)</h4>
<p>El gráfico de <code>checkresiduals()</code> ya incluye el resultado de esta prueba. La hipótesis nula es que los residuos son ruido blanco (no están autocorrelacionados).</p>
<ul>
<li>Resultado de la prueba Ljung-Box: El <code>p-value</code> es 0.518.</li>
</ul>
<p>Como este valor es mayor que 0.05, no podemos rechazar la hipótesis nula. Esto nos da confianza para concluir que los residuos no presentan autocorrelación significativa.</p>
</section>
<section id="prueba-de-normalidad-shapiro-wilk" class="level4" data-number="6.2.2">
<h4 data-number="6.2.2" class="anchored" data-anchor-id="prueba-de-normalidad-shapiro-wilk"><span class="header-section-number">6.2.2</span> Prueba de Normalidad (Shapiro-Wilk)</h4>
<p>Esta prueba evalúa si los residuos siguen una distribución normal.</p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: Los residuos se distribuyen normalmente.</p></li>
<li><p><span class="math inline">\(H_A\)</span>: Los residuos no se distribuyen normalmente.</p></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar la prueba de Shapiro-Wilk sobre los residuos</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(best_model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(best_model)
W = 0.96845, p-value = 0.111</code></pre>
</div>
</div>
<p>Resultado: El <code>p-value</code> es 0.111. Al ser mayor que 0.05, no rechazamos la hipótesis nula, lo que sugiere que podemos asumir que los residuos son normales.</p>
</section>
</section>
<section id="conclusión-de-la-validación" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="conclusión-de-la-validación"><span class="header-section-number">6.3</span> Conclusión de la Validación</h3>
<p>Tanto el análisis gráfico como las pruebas formales indican que los residuos de nuestro modelo ARIMA(0,1,0) se comportan como un ruido blanco. Por lo tanto, concluimos que el modelo está correctamente especificado y validado. Ahora podemos proceder con confianza al siguiente paso: la realización de pronósticos.</p>
<hr>
</section>
</section>
<section id="realizar-el-pronóstico" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="realizar-el-pronóstico"><span class="header-section-number">7</span> Realizar el Pronóstico</h2>
<p>Una vez que el modelo ha sido validado, podemos utilizarlo para su propósito principal: predecir valores futuros de la serie.</p>
<blockquote class="blockquote">
<p>Sobre el Pronóstico: “El pronóstico es una de las principales razones para el análisis de series de tiempo. Un modelo ARIMA puede ser proyectado hacia adelante para obtener pronósticos para periodos futuros. Estos pronósticos estarán acompañados de intervalos de confianza, que nos dan un rango de valores probables para la serie.”</p>
<p>— Enders, W. (2015). Applied Econometric Time Series (4th ed.).</p>
</blockquote>
<p>Utilizaremos la función <code>forecast()</code> para generar predicciones para los próximos 5 años.</p>
<section id="generación-del-pronóstico" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="generación-del-pronóstico"><span class="header-section-number">7.1</span> Generación del Pronóstico</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generar el pronóstico para los próximos 5 periodos (h=5)</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># El modelo ya está guardado en el objeto 'best_model'</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>pib_forecast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(best_model, <span class="at">h =</span> <span class="dv">5</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los valores del pronóstico</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>pib_forecast</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     Point Forecast        Lo 80        Hi 80        Lo 95        Hi 95
2022   622047613564 594012021934 650083205195 579170876211 664924350918
2023   622047613564 582399299651 661695927478 561410750088 682684477041
2024   622047613564 573488544440 670606682689 547782926005 696312301124
2025   622047613564 565976430303 678118796826 536294138857 707801088272
2026   622047613564 559358124889 684737102240 526172314188 717922912941</code></pre>
</div>
</div>
<p>Interpretación: La tabla muestra el pronóstico puntual (<code>Point Forecast</code>) para los próximos 5 años, junto con los intervalos de confianza al 80% (<code>Lo 80</code>, <code>Hi 80</code>) y al 95% (<code>Lo 95</code>, <code>Hi 95</code>). Por ejemplo, el pronóstico para el próximo año es de 6.2204761^{11}.</p>
</section>
<section id="visualización-del-pronóstico" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="visualización-del-pronóstico"><span class="header-section-number">7.2</span> Visualización del Pronóstico</h3>
<p>La forma más efectiva de evaluar un pronóstico es visualizándolo junto con los datos históricos.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar el pronóstico</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(pib_forecast) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Pronóstico del PIB de Argentina con Modelo ARIMA(0,1,0)"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Predicciones a 5 años con intervalos de confianza al 80% y 95%"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Año"</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"PIB (en unidades monetarias)"</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Metodología-Box-Jenkins-para-Modelos-ARIMA_files/figure-html/plot-forecast-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Pronóstico del PIB de Argentina para los próximos 5 años.</figcaption>
</figure>
</div>
</div>
</div>
<p>Interpretación del Gráfico: El gráfico muestra la serie histórica del PIB en negro. La línea azul representa el pronóstico puntual, que, como es de esperar de un modelo de caminata aleatoria, proyecta el último valor observado con una cierta deriva. Las áreas sombreadas en azul claro y oscuro representan los intervalos de confianza al 95% y 80%, respectivamente. Es importante notar cómo la incertidumbre (el ancho de los intervalos) aumenta a medida que nos alejamos en el futuro.</p>
<hr>
</section>
</section>
<section id="validación-de-la-predicción" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="validación-de-la-predicción"><span class="header-section-number">8</span> Validación de la Predicción</h2>
<p>Generar un pronóstico es solo la mitad del trabajo. Para confiar en nuestras predicciones, debemos evaluar su precisión. La mejor manera de hacerlo es mediante una validación fuera de muestra (out-of-sample).</p>
<blockquote class="blockquote">
<p>Evaluación del Pronóstico: “Una prueba útil de la fiabilidad de un modelo de pronóstico es retener algunos de los datos al final de la serie de tiempo, estimar el modelo utilizando solo los datos anteriores, y luego usar el modelo para ‘pronosticar’ los datos retenidos. Comparando estos pronósticos con los valores reales, se puede calcular la precisión del modelo.”</p>
<p>— Pindyck, R. S., &amp; Rubinfeld, D. L. (2001). Econometría: Modelos y Pronósticos (4a ed.).</p>
</blockquote>
<section id="preparación-de-los-datos-para-validación" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="preparación-de-los-datos-para-validación"><span class="header-section-number">8.1</span> Preparación de los Datos para Validación</h3>
<p>Dividiremos nuestra serie <code>pib_ts</code> en dos partes:</p>
<ul>
<li>Conjunto de Entrenamiento (<code>train</code>): Datos desde 1960 hasta 2017.</li>
</ul>
<!-- -->
<ul>
<li>Conjunto de Prueba (<code>test</code>): Datos desde 2018 hasta 2021.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dividir la serie de tiempo</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>pib_train <span class="ot">&lt;-</span> <span class="fu">window</span>(pib_ts, <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">2017</span>, <span class="dv">1</span>))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>pib_test <span class="ot">&lt;-</span> <span class="fu">window</span>(pib_ts, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">2018</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="re-estimación-y-pronóstico-fuera-de-muestra" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="re-estimación-y-pronóstico-fuera-de-muestra"><span class="header-section-number">8.2</span> Re-estimación y Pronóstico Fuera de Muestra</h3>
<p>Ahora, ajustamos nuestro modelo ARIMA(0,1,0) usando solo el conjunto de entrenamiento y pronosticamos el número de periodos que contiene nuestro conjunto de prueba.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-estimar el modelo solo con los datos de entrenamiento</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>model_train <span class="ot">&lt;-</span> <span class="fu">Arima</span>(pib_train, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generar el pronóstico para el horizonte del conjunto de prueba</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>forecast_validation <span class="ot">&lt;-</span> <span class="fu">forecast</span>(model_train, <span class="at">h =</span> <span class="fu">length</span>(pib_test))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="cálculo-de-las-métricas-de-precisión" class="level3" data-number="8.3">
<h3 data-number="8.3" class="anchored" data-anchor-id="cálculo-de-las-métricas-de-precisión"><span class="header-section-number">8.3</span> Cálculo de las Métricas de Precisión</h3>
<p>La función <code>accuracy()</code> del paquete <code>forecast</code> es ideal para esta tarea. Compara los valores pronosticados con los valores reales del conjunto de prueba y calcula varias métricas de error.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular y mostrar las métricas de precisión</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(forecast_validation, pib_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                       ME        RMSE         MAE       MPE     MAPE     MASE
Training set   8183420239 20163864308 15549373354  2.313270 4.394117 0.982923
Test set     -16713367129 29750684731 24721725798 -2.914114 4.162879 1.562735
                    ACF1 Theil's U
Training set  0.17752247        NA
Test set     -0.02777693 0.7280038</code></pre>
</div>
</div>
<p>Interpretación de las Métricas: * RMSE (Root Mean Squared Error): La raíz del error cuadrático medio. Es una de las métricas más populares. Nos dice, en promedio, qué tan lejos están nuestras predicciones de los valores reales, en las mismas unidades que la serie original. Un valor más bajo es mejor.</p>
<ul>
<li><p>MAE (Mean Absolute Error): El error absoluto medio. Similar al RMSE pero menos sensible a errores grandes. También se interpreta en las unidades originales de la serie. Un valor más bajo es mejor.</p></li>
<li><p>MAPE (Mean Absolute Percentage Error): El error porcentual absoluto medio. Expresa el error como un porcentaje, lo que es útil para comparar la precisión entre series de diferentes escalas. Un valor más bajo es mejor.</p></li>
<li><p>Theil’s U: Compara la precisión de nuestro modelo con un pronóstico ingenuo (que simplemente predice que el próximo valor será igual al último valor observado). Un valor menor a 1 indica que nuestro modelo es mejor que el pronóstico ingenuo.</p></li>
</ul>
</section>
<section id="conclusión-de-la-validación-1" class="level3" data-number="8.4">
<h3 data-number="8.4" class="anchored" data-anchor-id="conclusión-de-la-validación-1"><span class="header-section-number">8.4</span> Conclusión de la Validación</h3>
<p>Al analizar estas métricas, podemos cuantificar la capacidad predictiva de nuestro modelo ARIMA(0,1,0). Esta evaluación objetiva es fundamental antes de utilizar los resultados del modelo para la toma de decisiones.</p>
<hr>
</section>
</section>
<section id="utilización-de-los-resultados-para-la-toma-de-decisiones" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="utilización-de-los-resultados-para-la-toma-de-decisiones"><span class="header-section-number">9</span> Utilización de los Resultados para la Toma de Decisiones</h2>
<p>El paso final de la metodología consiste en traducir los resultados estadísticos en información útil para la toma de decisiones. Un pronóstico, por muy preciso que sea, solo es valioso si informa y mejora la planificación estratégica.</p>
<blockquote class="blockquote">
<p>El Propósito del Modelado: “El objetivo final del modelado econométrico no es simplemente encontrar el modelo con el mejor ajuste estadístico, sino obtener información útil sobre el mundo real. Los pronósticos, las simulaciones de políticas y las pruebas de hipótesis son las herramientas mediante las cuales la econometría puede informar las decisiones económicas y empresariales.”</p>
<p>— Wooldridge, J. M. (2009). Introductory econometrics: A modern approach (4th ed.).</p>
</blockquote>
<section id="aplicaciones-prácticas-del-pronóstico-del-pib" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="aplicaciones-prácticas-del-pronóstico-del-pib"><span class="header-section-number">9.1</span> Aplicaciones Prácticas del Pronóstico del PIB</h3>
<p>Los resultados de nuestro modelo ARIMA(0,1,0) para el PIB de Argentina pueden ser utilizados en diversos contextos:</p>
<ul>
<li>Planificación Gubernamental: El gobierno puede utilizar el pronóstico de crecimiento del PIB para estimar los ingresos fiscales futuros, planificar el presupuesto nacional y ajustar las políticas fiscales y monetarias. Un pronóstico de crecimiento lento podría sugerir la necesidad de políticas de estímulo.</li>
<li>Estrategia Empresarial: Las empresas pueden usar las proyecciones del PIB como un indicador de la salud general de la economía. Esto puede influir en decisiones de inversión, expansión, contratación de personal y gestión de inventarios. Por ejemplo, una empresa podría posponer una gran inversión si el pronóstico del PIB es pesimista.</li>
<li>Análisis de Inversiones: Los inversores y analistas financieros utilizan los pronósticos del PIB para evaluar el clima de inversión de un país. Un crecimiento económico robusto puede atraer inversión extranjera y afectar el rendimiento de los mercados de acciones y bonos.</li>
<li>Gestión de Riesgos: Los intervalos de confianza de nuestro pronóstico son tan importantes como la predicción puntual. El rango de valores probables (indicado por las áreas sombreadas en nuestro gráfico) ayuda a las organizaciones a prepararse para diferentes escenarios (optimista, pesimista) y a gestionar los riesgos asociados con la incertidumbre económica.</li>
</ul>
</section>
<section id="limitaciones-y-consideraciones" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="limitaciones-y-consideraciones"><span class="header-section-number">9.2</span> Limitaciones y Consideraciones</h3>
<p>Es crucial recordar que nuestro modelo es un modelo univariado simple. Se basa únicamente en el comportamiento pasado de la propia serie del PIB. No incorpora otras variables que claramente afectan a la economía, como la inflación, las tasas de interés, la política fiscal o los shocks externos.</p>
<p>Por lo tanto, si bien nuestro modelo ARIMA(0,1,0) proporciona un punto de referencia sólido y una predicción de línea base, para decisiones de alta importancia, debería ser complementado con modelos más complejos (como modelos VAR o VEC) y con el juicio de expertos.</p>
<hr>
</section>
</section>
<section id="conclusión-general-del-taller" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="conclusión-general-del-taller"><span class="header-section-number">10</span> Conclusión General del Taller</h2>
<p>A lo largo de este taller, hemos aplicado de manera rigurosa la metodología Box-Jenkins para analizar y pronosticar la serie del PIB de Argentina. Partiendo de una serie no estacionaria, realizamos las transformaciones necesarias, identificamos una estructura de modelo parsimoniosa, estimamos sus parámetros y validamos exhaustivamente sus residuos y su capacidad predictiva.</p>
<p>El resultado es un modelo ARIMA(0,1,0) validado que, aunque simple, sirve como un ejemplo claro y reproducible de todo el flujo de trabajo econométrico, desde el análisis de datos hasta la generación de información valiosa para la toma de decisiones.</p>
<hr>
</section>
<section id="referencias" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="referencias"><span class="header-section-number">11</span> Referencias</h2>
<ul>
<li>Enders, W. (2015). Applied Econometric Time Series (4th ed.). Wiley.</li>
<li>Gujarati, D. N., &amp; Porter, D. C. (2009). Econometría (5a ed.). McGraw-Hill.</li>
<li>Pindyck, R. S., &amp; Rubinfeld, D. L. (2001). Econometría: Modelos y Pronósticos (4a ed.). McGraw-Hill.</li>
<li>Wooldridge, J. M. (2009). Introductory econometrics: A modern approach (4th ed.). Cengage Learning.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/yuberley20\.github\.io\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2025, Yuberley Cruz Caycedo</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Construido con <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>