<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yuberley Cruz Caycedo">

<title>Informe sobre el Metodo de los Momentos Simulados para un Modelo RBC – Yuberley Cruz Caycedo | Portafolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c82218b12ac0f327fa8bd7d074ce2147.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Yuberley Cruz Caycedo | Portafolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">Sobre Mí</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../proyectos.html"> 
<span class="menu-text">Proyectos</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-macroeconomía-dinámica" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Macroeconomía Dinámica</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-macroeconomía-dinámica">    
        <li>
    <a class="dropdown-item" href="../Macroeconomia_Dinamica/Transcripcion_Modelo_Busqueda.html">
 <span class="dropdown-text">Modelo de Búsqueda y Emparejamiento</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Macroeconomia_Dinamica/Proyecto_final_Practicas.html">
 <span class="dropdown-text">Fricciones, Informalidad y Dinámica Laboral: La Imperativa Necesidad de los Modelos de Búsqueda y Emparejamiento en el Análisis del Mercado Laboral Colombiano</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Macroeconomia_Dinamica/KPR (Solución análitica).html">
 <span class="dropdown-text">Modelo de King Prócer y Rebelo (KPR) mediante una solución análitica</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Macroeconomia_Dinamica/Informe_sobre_MMS_para_un_Modelo_RBC.html">
 <span class="dropdown-text">Informe sobre el Metodo de los Momentos Simulados para un Modelo RBC</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/yuberley20"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/yuberley-cruz-caycedo-b805731bby"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#informe-sobre-el-método-de-momentos-simulados-mms-para-un-modelo-de-ciclo-económico-real-rbc-1" id="toc-informe-sobre-el-método-de-momentos-simulados-mms-para-un-modelo-de-ciclo-económico-real-rbc-1" class="nav-link active" data-scroll-target="#informe-sobre-el-método-de-momentos-simulados-mms-para-un-modelo-de-ciclo-económico-real-rbc-1">Informe sobre el Método de Momentos Simulados (MMS) para un Modelo de Ciclo Económico Real (RBC)</a></li>
  <li><a href="#especificación-del-modelo-económico" id="toc-especificación-del-modelo-económico" class="nav-link" data-scroll-target="#especificación-del-modelo-económico">Especificación del Modelo Económico</a>
  <ul class="collapse">
  <li><a href="#el-problema-del-hogar-representativo" id="toc-el-problema-del-hogar-representativo" class="nav-link" data-scroll-target="#el-problema-del-hogar-representativo">El Problema del Hogar Representativo</a></li>
  <li><a href="#decisión-de-consumo-con-hábitos" id="toc-decisión-de-consumo-con-hábitos" class="nav-link" data-scroll-target="#decisión-de-consumo-con-hábitos">Decisión de Consumo (con Hábitos)</a></li>
  <li><a href="#decisión-de-ocio-y-trabajo" id="toc-decisión-de-ocio-y-trabajo" class="nav-link" data-scroll-target="#decisión-de-ocio-y-trabajo">Decisión de Ocio y Trabajo</a></li>
  <li><a href="#decisión-de-ahorro-ecuación-de-euler-del-capital" id="toc-decisión-de-ahorro-ecuación-de-euler-del-capital" class="nav-link" data-scroll-target="#decisión-de-ahorro-ecuación-de-euler-del-capital">Decisión de Ahorro (Ecuación de Euler del Capital)</a></li>
  <li><a href="#el-problema-de-la-empresa-representativa" id="toc-el-problema-de-la-empresa-representativa" class="nav-link" data-scroll-target="#el-problema-de-la-empresa-representativa">El Problema de la Empresa Representativa</a></li>
  <li><a href="#función-de-producción" id="toc-función-de-producción" class="nav-link" data-scroll-target="#función-de-producción">Función de Producción</a></li>
  <li><a href="#decisiones-de-demanda-de-factores" id="toc-decisiones-de-demanda-de-factores" class="nav-link" data-scroll-target="#decisiones-de-demanda-de-factores">Decisiones de Demanda de Factores</a></li>
  <li><a href="#cierre-del-modelo-y-ecuaciones-agregadas" id="toc-cierre-del-modelo-y-ecuaciones-agregadas" class="nav-link" data-scroll-target="#cierre-del-modelo-y-ecuaciones-agregadas">Cierre del Modelo y Ecuaciones Agregadas</a></li>
  <li><a href="#restricción-de-recursos-agregada" id="toc-restricción-de-recursos-agregada" class="nav-link" data-scroll-target="#restricción-de-recursos-agregada">Restricción de Recursos Agregada</a></li>
  <li><a href="#ley-de-acumulación-de-capital" id="toc-ley-de-acumulación-de-capital" class="nav-link" data-scroll-target="#ley-de-acumulación-de-capital">Ley de Acumulación de Capital</a></li>
  <li><a href="#proceso-de-productividad" id="toc-proceso-de-productividad" class="nav-link" data-scroll-target="#proceso-de-productividad">Proceso de Productividad</a></li>
  </ul></li>
  <li><a href="#implementación-y-calibración-en-dynare" id="toc-implementación-y-calibración-en-dynare" class="nav-link" data-scroll-target="#implementación-y-calibración-en-dynare">Implementación y Calibración en Dynare</a>
  <ul class="collapse">
  <li><a href="#preámbulo-declaración-de-componentes-del-modelo" id="toc-preámbulo-declaración-de-componentes-del-modelo" class="nav-link" data-scroll-target="#preámbulo-declaración-de-componentes-del-modelo">Preámbulo: Declaración de Componentes del Modelo</a></li>
  <li><a href="#variables-endógenas-y-de-estado" id="toc-variables-endógenas-y-de-estado" class="nav-link" data-scroll-target="#variables-endógenas-y-de-estado">Variables Endógenas y de Estado</a></li>
  <li><a href="#shocks-exógenos" id="toc-shocks-exógenos" class="nav-link" data-scroll-target="#shocks-exógenos">Shocks Exógenos</a>
  <ul class="collapse">
  <li><a href="#parámetros-y-calibración-base" id="toc-parámetros-y-calibración-base" class="nav-link" data-scroll-target="#parámetros-y-calibración-base">Parámetros y Calibración Base</a></li>
  </ul></li>
  <li><a href="#el-bloque-model-ecuaciones-estructurales" id="toc-el-bloque-model-ecuaciones-estructurales" class="nav-link" data-scroll-target="#el-bloque-model-ecuaciones-estructurales">El Bloque <code>model</code>: Ecuaciones Estructurales</a>
  <ul class="collapse">
  <li><a href="#ecuaciones-del-hogar" id="toc-ecuaciones-del-hogar" class="nav-link" data-scroll-target="#ecuaciones-del-hogar">Ecuaciones del Hogar</a></li>
  <li><a href="#ecuaciones-de-la-empresa" id="toc-ecuaciones-de-la-empresa" class="nav-link" data-scroll-target="#ecuaciones-de-la-empresa">Ecuaciones de la Empresa</a></li>
  <li><a href="#ecuaciones-de-cierre-y-dinámica-agregada" id="toc-ecuaciones-de-cierre-y-dinámica-agregada" class="nav-link" data-scroll-target="#ecuaciones-de-cierre-y-dinámica-agregada">Ecuaciones de Cierre y Dinámica Agregada</a></li>
  </ul></li>
  <li><a href="#el-bloque-steady_state_model-cálculo-del-equilibrio-a-largo-plazo" id="toc-el-bloque-steady_state_model-cálculo-del-equilibrio-a-largo-plazo" class="nav-link" data-scroll-target="#el-bloque-steady_state_model-cálculo-del-equilibrio-a-largo-plazo">El Bloque <code>steady_state_model</code>: Cálculo del Equilibrio a Largo Plazo</a></li>
  </ul></li>
  <li><a href="#estimación-por-método-de-momentos-simulado-smm" id="toc-estimación-por-método-de-momentos-simulado-smm" class="nav-link" data-scroll-target="#estimación-por-método-de-momentos-simulado-smm">Estimación por Método de Momentos Simulado (SMM)</a>
  <ul class="collapse">
  <li><a href="#parámetros-a-estimar" id="toc-parámetros-a-estimar" class="nav-link" data-scroll-target="#parámetros-a-estimar">Parámetros a Estimar</a></li>
  <li><a href="#momentos-a-igualar" id="toc-momentos-a-igualar" class="nav-link" data-scroll-target="#momentos-a-igualar">Momentos a Igualar</a></li>
  <li><a href="#parámetros-estructurales-estimados" id="toc-parámetros-estructurales-estimados" class="nav-link" data-scroll-target="#parámetros-estructurales-estimados">Parámetros Estructurales Estimados</a></li>
  <li><a href="#prueba-de-especificación-del-modelo-prueba-j" id="toc-prueba-de-especificación-del-modelo-prueba-j" class="nav-link" data-scroll-target="#prueba-de-especificación-del-modelo-prueba-j">Prueba de Especificación del Modelo (Prueba J)</a></li>
  <li><a href="#análisis-del-ajuste-de-los-momentos" id="toc-análisis-del-ajuste-de-los-momentos" class="nav-link" data-scroll-target="#análisis-del-ajuste-de-los-momentos">Análisis del Ajuste de los Momentos</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Informe sobre el Metodo de los Momentos Simulados para un Modelo RBC</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Yuberley Cruz Caycedo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">11 de julio de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="column-page" style="text-align: center; max-width: 800px; margin: 0 auto; padding: 20px;">
<p><br></p>
<section id="informe-sobre-el-método-de-momentos-simulados-mms-para-un-modelo-de-ciclo-económico-real-rbc" class="level1">
<h1>Informe sobre el Método de Momentos Simulados (MMS) para un Modelo de Ciclo Económico Real (RBC)</h1>
<p><br></p>
<section id="yuberley-cruz-caycedo" class="level3">
<h3 class="anchored" data-anchor-id="yuberley-cruz-caycedo"><strong>Yuberley Cruz Caycedo</strong></h3>
<p><em>Practicante Banco de la República de Colombia</em></p>
<p><br><br></p>
<p><strong>Presentado a:</strong> Catalina Granda Carvajal <br> <small>cgranda@banrep.gov.co, Investigadora senior Banco de la República</small></p>
<p><br><br></p>
<section id="de-agosto-de-2025" class="level4">
<h4 class="anchored" data-anchor-id="de-agosto-de-2025">2 de Agosto de 2025</h4>
<p><br></p>
<div style="text-align: left; background-color: rgba(255,255,255,0.05); padding: 20px; border-radius: 5px;">
<p><strong>Universidad Nacional de Colombia</strong> - Sede Medellín</p>
<p><strong>Facultad de Ciencias Humanas y Económicas</strong></p>
</div>
</section>
</section>
</section>
</div>
<section id="informe-sobre-el-método-de-momentos-simulados-mms-para-un-modelo-de-ciclo-económico-real-rbc-1" class="level1">
<h1>Informe sobre el Método de Momentos Simulados (MMS) para un Modelo de Ciclo Económico Real (RBC)</h1>
<p>El siguiente informe viene dado por la necesidad de desglosar el metodo de momentos simulados (MMS) explicado en el curso de modelos de equilibrio general estocásticos (DSGE). En este caso trabajamos con los scripts y los datos trabajados en la clases. El modelo a trabajar esta basado en los trabajos de Andreasen, Fernández-Villaverde, Rubio-Ramírez (2018)</p>
</section>
<section id="especificación-del-modelo-económico" class="level1">
<h1>Especificación del Modelo Económico</h1>
<p>En esta sección, se presenta la estructura matemática de un modelo de Ciclos Económicos Reales (RBC) con formación de hábitos en el consumo. El modelo consta de dos agentes principales: un hogar representativo y una empresa representativa, dentro de una economía cerrada y sin gobierno.</p>
<section id="el-problema-del-hogar-representativo" class="level2">
<h2 class="anchored" data-anchor-id="el-problema-del-hogar-representativo">El Problema del Hogar Representativo</h2>
<p>El hogar representativo busca maximizar su utilidad esperada de por vida, sujeta a su restricción presupuestaria. Las decisiones óptimas del hogar se resumen en las siguientes condiciones de primer orden.</p>
</section>
<section id="decisión-de-consumo-con-hábitos" class="level2">
<h2 class="anchored" data-anchor-id="decisión-de-consumo-con-hábitos">Decisión de Consumo (con Hábitos)</h2>
<p>La presencia de hábitos externos (<span class="math inline">\(B \cdot C_{t-1}\)</span>) en la función de utilidad modifica la ecuación de Euler estándar. La condición de optimalidad para el consumo ( <a href="#eq-foc-c" class="quarto-xref">Ecuación&nbsp;1</a>) iguala la utilidad marginal de la riqueza (<span class="math inline">\(\lambda_t\)</span>) con el beneficio marginal del consumo hoy, neto del costo de formar un hábito más fuerte para mañana.</p>
<p><span id="eq-foc-c"><span class="math display">\[\lambda_t = (C_t - B \cdot C_{t-1})^{-\eta_c} - \beta B \cdot E_t[(C_{t+1} - B \cdot C_t)^{-\eta_c}]  \tag{1}\]</span></span></p>
</section>
<section id="decisión-de-ocio-y-trabajo" class="level2">
<h2 class="anchored" data-anchor-id="decisión-de-ocio-y-trabajo">Decisión de Ocio y Trabajo</h2>
<p>La condición de optimalidad para la oferta de trabajo ( <a href="#eq-foc-n" class="quarto-xref">Ecuación&nbsp;2</a>) establece que el hogar elige trabajar (<span class="math inline">\(N_t\)</span>) hasta el punto en que la desutilidad marginal de una hora extra es exactamente igual a la utilidad marginal que obtendría del salario real (<span class="math inline">\(W_t\)</span>) ganado en esa hora.</p>
<p><span id="eq-foc-n"><span class="math display">\[\theta(1-N_t)^{-\eta_l} = \lambda_t W_t  \tag{2}\]</span></span></p>
</section>
<section id="decisión-de-ahorro-ecuación-de-euler-del-capital" class="level2">
<h2 class="anchored" data-anchor-id="decisión-de-ahorro-ecuación-de-euler-del-capital">Decisión de Ahorro (Ecuación de Euler del Capital)</h2>
<p>Finalmente, la decisión intertemporal de ahorro ( <a href="#eq-euler-k" class="quarto-xref">Ecuación&nbsp;3</a>) conecta el presente con el futuro. Iguala el costo de ahorrar una unidad hoy (la utilidad a la que se renuncia, <span class="math inline">\(\lambda_t\)</span>) con el beneficio esperado del rendimiento del capital mañana.</p>
<p><span id="eq-euler-k"><span class="math display">\[\lambda_t = \beta E_t[\lambda_{t+1}(r^k_{t+1} + 1 - \delta)]  \tag{3}\]</span></span></p>
<p>Donde <span class="math inline">\(r^k_{t+1}\)</span> es la tasa de alquiler del capital y <span class="math inline">\(\delta\)</span> es la tasa de depreciación.</p>
</section>
<section id="el-problema-de-la-empresa-representativa" class="level2">
<h2 class="anchored" data-anchor-id="el-problema-de-la-empresa-representativa">El Problema de la Empresa Representativa</h2>
<p>La economía cuenta con una empresa representativa que opera en mercados competitivos. Su objetivo es maximizar los beneficios contratando trabajo y alquilando capital para producir el único bien de la economía, utilizando la tecnología descrita por la siguiente función de producción.</p>
</section>
<section id="función-de-producción" class="level2">
<h2 class="anchored" data-anchor-id="función-de-producción">Función de Producción</h2>
<p>La tecnología se representa mediante una función de producción Cobb-Douglas ( <a href="#eq-prod-func" class="quarto-xref">Ecuación&nbsp;4</a>) que combina capital (<span class="math inline">\(K_t\)</span>) y trabajo (<span class="math inline">\(N_t\)</span>) para generar producto (<span class="math inline">\(Y_t\)</span>), dada la productividad (<span class="math inline">\(A_t\)</span>).</p>
<p><span id="eq-prod-func"><span class="math display">\[Y_t = A_t K_t^{1-\alpha} N_t^\alpha  \tag{4}\]</span></span></p>
</section>
<section id="decisiones-de-demanda-de-factores" class="level2">
<h2 class="anchored" data-anchor-id="decisiones-de-demanda-de-factores">Decisiones de Demanda de Factores</h2>
<p>Para maximizar sus beneficios, la empresa demanda capital y trabajo hasta que el costo de cada factor iguala su producto marginal. La demanda de capital ( <a href="#eq-foc-k" class="quarto-xref">Ecuación&nbsp;5</a>) iguala la tasa de alquiler (<span class="math inline">\(r^k_t\)</span>) al producto marginal del capital (PMK).</p>
<p><span id="eq-foc-k"><span class="math display">\[r^k_t = (1-\alpha) A_t K_t^{-\alpha} N_t^\alpha  \tag{5}\]</span></span></p>
<p>De manera análoga, la demanda de trabajo ( <a href="#eq-foc-l" class="quarto-xref">Ecuación&nbsp;6</a>) iguala el salario real (<span class="math inline">\(W_t\)</span>) al producto marginal del trabajo (PML).</p>
<p><span id="eq-foc-l"><span class="math display">\[W_t = \alpha A_t K_t^{1-\alpha} N_t^{\alpha-1} \tag{6}\]</span></span></p>
</section>
<section id="cierre-del-modelo-y-ecuaciones-agregadas" class="level2">
<h2 class="anchored" data-anchor-id="cierre-del-modelo-y-ecuaciones-agregadas">Cierre del Modelo y Ecuaciones Agregadas</h2>
<p>Finalmente, las siguientes ecuaciones aseguran la consistencia contable de la economía y describen la evolución de las variables de estado.</p>
</section>
<section id="restricción-de-recursos-agregada" class="level2">
<h2 class="anchored" data-anchor-id="restricción-de-recursos-agregada">Restricción de Recursos Agregada</h2>
<p>La restricción de recursos ( <a href="#eq-resource" class="quarto-xref">Ecuación&nbsp;7</a>) establece que toda la producción se destina a consumo o inversión. Es la condición de equilibrio del mercado de bienes.</p>
<p><span id="eq-resource"><span class="math display">\[Y_t = C_t + I_t ç \tag{7}\]</span></span></p>
</section>
<section id="ley-de-acumulación-de-capital" class="level2">
<h2 class="anchored" data-anchor-id="ley-de-acumulación-de-capital">Ley de Acumulación de Capital</h2>
<p>Esta ley ( <a href="#eq-capital-accum" class="quarto-xref">Ecuación&nbsp;8</a>) describe cómo la inversión de hoy (<span class="math inline">\(I_t\)</span>) se convierte en el capital disponible para mañana (<span class="math inline">\(K_{t+1}\)</span>).</p>
<p><span id="eq-capital-accum"><span class="math display">\[K_{t+1} = (1-\delta)K_t + I_t  \tag{8}\]</span></span></p>
</section>
<section id="proceso-de-productividad" class="level2">
<h2 class="anchored" data-anchor-id="proceso-de-productividad">Proceso de Productividad</h2>
<p>La productividad total de los factores (<span class="math inline">\(A_t\)</span>) sigue un proceso autorregresivo de orden 1 (AR(1)) en logaritmos ( <a href="#eq-tech-proc" class="quarto-xref">Ecuación&nbsp;9</a>), donde <span class="math inline">\(\rho_a\)</span> es la persistencia y <span class="math inline">\(\epsilon^a_t\)</span> es un shock aleatorio con media cero.</p>
<p><span id="eq-tech-proc"><span class="math display">\[\log(A_t) = \rho_a \log(A_{t-1}) + \epsilon^a_t  \tag{9}\]</span></span></p>
</section>
</section>
<section id="implementación-y-calibración-en-dynare" class="level1">
<h1>Implementación y Calibración en Dynare</h1>
<p>Esta sección traduce la teoría económica descrita en la Sección 1 a un script que el software Dynare puede interpretar, resolver y estimar. El código se divide en tres partes principales: el preámbulo, donde se declaran los componentes; el bloque del modelo, donde se especifican las ecuaciones; y el bloque del estado estacionario, que guía a Dynare para encontrar el equilibrio a largo plazo.</p>
<section id="preámbulo-declaración-de-componentes-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="preámbulo-declaración-de-componentes-del-modelo">Preámbulo: Declaración de Componentes del Modelo</h2>
<p>El script comienza declarando todos los elementos necesarios: variables, shocks y parámetros.</p>
</section>
<section id="variables-endógenas-y-de-estado" class="level2">
<h2 class="anchored" data-anchor-id="variables-endógenas-y-de-estado">Variables Endógenas y de Estado</h2>
<p>Primero, se declaran todas las variables endógenas (aquellas determinadas dentro del modelo) con el comando <code>var</code>. Es una convención en este script trabajar con el logaritmo de las variables económicas reales. El comando <code>predetermined_variables</code> es crucial para indicarle a Dynare que el capital, <code>k</code>, es una variable de estado cuyo valor en el período <span class="math inline">\(t\)</span> ya es conocido en <span class="math inline">\(t-1\)</span>.</p>
<pre class="text"><code>% Declaración de variables endógenas (en logaritmos)
var k c a iv y la n rk w;

% Especificación de la variable de estado
predetermined_variables k;</code></pre>
</section>
<section id="shocks-exógenos" class="level2">
<h2 class="anchored" data-anchor-id="shocks-exógenos">Shocks Exógenos</h2>
<p>A continuación, se declara el shock exógeno de productividad con el comando <code>varexo</code>. Este es el único impulso aleatorio que afecta a la economía.</p>
<pre class="text"><code>% Declaración de la innovación al proceso de productividad
varexo u_a;</code></pre>
<section id="parámetros-y-calibración-base" class="level3">
<h3 class="anchored" data-anchor-id="parámetros-y-calibración-base">Parámetros y Calibración Base</h3>
<p>Finalmente, se declaran los nombres de todos los parámetros estructurales con <code>parameters</code> y se les asigna un valor numérico. Estos valores sirven como una calibración base, que se utilizará para resolver el estado estacionario y como punto de partida para el proceso de estimación posterior.</p>
<pre class="text"><code>% Declaración de los nombres de los parámetros
parameters DELTA BETTA B ETAl ETAc THETA ALFA RHOA;

% Asignación de valores (calibración)
DELTA = 0.025;   // Tasa de depreciación ($\delta$)
BETTA = 0.984;   // Factor de descuento ($\beta$)
B     = 0.5;     // Hábito de consumo (B)
ETAl  = 1;       // Inversa de la elasticidad de Frisch ($\eta_{l}$)
ETAc  = 2;       // Aversión al riesgo ($\eta_{c}$)
THETA = 3.48;    // Peso del ocio ($\theta$)
ALFA  = 0.667;   // Participación del trabajo ($\alpha$)
RHOA  = 0.979;   // Persistencia de la productividad ($\rhoa_{a}$)</code></pre>
</section>
</section>
<section id="el-bloque-model-ecuaciones-estructurales" class="level2">
<h2 class="anchored" data-anchor-id="el-bloque-model-ecuaciones-estructurales">El Bloque <code>model</code>: Ecuaciones Estructurales</h2>
<p>Esta es la sección central del script, donde se transcriben las condiciones de optimalidad y las ecuaciones de contabilidad del modelo. Dado que las variables se declararon como logaritmos, se utiliza la función <code>exp()</code> para trabajar con sus niveles. La notación <code>(+1)</code> se refiere al valor esperado del próximo período y <code>(-1)</code> al valor del período anterior.</p>
<pre class="text"><code>model;</code></pre>
<section id="ecuaciones-del-hogar" class="level3">
<h3 class="anchored" data-anchor-id="ecuaciones-del-hogar">Ecuaciones del Hogar</h3>
<p>Las primeras tres ecuaciones corresponden a las condiciones de primer orden del problema de maximización de utilidad del hogar.</p>
<section id="ecuación-1-optimalidad-del-consumo-con-hábitos" class="level5">
<h5 class="anchored" data-anchor-id="ecuación-1-optimalidad-del-consumo-con-hábitos">Ecuación 1: Optimalidad del Consumo (con Hábitos)</h5>
<p>Corresponde a la Ecuación Matemática <a href="#eq-foc-c" class="quarto-xref">Ecuación&nbsp;1</a>.</p>
<pre class="text"><code>0 = -exp(la) + (exp(c)-B*exp(c(-1)))^(-ETAc) - BETTA*B*(exp(c(+1))-B*exp(c))^(-ETAc);</code></pre>
</section>
<section id="ecuación-2-optimalidad-del-trabajo" class="level5">
<h5 class="anchored" data-anchor-id="ecuación-2-optimalidad-del-trabajo">Ecuación 2: Optimalidad del Trabajo</h5>
<p>Corresponde a la Ecuación Matemática <a href="#eq-foc-n" class="quarto-xref">Ecuación&nbsp;2</a>}.</p>
<pre class="text"><code>0 = -THETA*(1-exp(n))^-ETAl + exp(la)*exp(w);</code></pre>
</section>
<section id="ecuación-3-ecuación-de-euler-del-capital" class="level5">
<h5 class="anchored" data-anchor-id="ecuación-3-ecuación-de-euler-del-capital">Ecuación 3: Ecuación de Euler del Capital</h5>
<p>Corresponde a la Ecuación Matemática <a href="#eq-euler-k" class="quarto-xref">Ecuación&nbsp;3</a>.</p>
<pre class="text"><code>0 = -exp(la) + BETTA*exp(la(+1))*(exp(rk(+1)) + (1-DELTA));</code></pre>
</section>
</section>
<section id="ecuaciones-de-la-empresa" class="level3">
<h3 class="anchored" data-anchor-id="ecuaciones-de-la-empresa">Ecuaciones de la Empresa</h3>
<p>Las siguientes ecuaciones describen las decisiones de la empresa para maximizar sus beneficios, basadas en su tecnología.</p>
<section id="ecuación-4-demanda-de-capital" class="level5">
<h5 class="anchored" data-anchor-id="ecuación-4-demanda-de-capital">Ecuación 4: Demanda de Capital</h5>
<p>Corresponde a la Ecuación Matemática <a href="#eq-foc-k" class="quarto-xref">Ecuación&nbsp;5</a>, que iguala la tasa de alquiler del capital a su producto marginal.</p>
<pre class="text"><code>0 = -exp(a)*(1-ALFA)*exp(k)^(-ALFA)*exp(n)^(ALFA) + exp(rk);</code></pre>
</section>
<section id="ecuación-5-demanda-de-trabajo" class="level5">
<h5 class="anchored" data-anchor-id="ecuación-5-demanda-de-trabajo">Ecuación 5: Demanda de Trabajo</h5>
<p>Corresponde a la Ecuación Matemática <a href="#eq-foc-l" class="quarto-xref">Ecuación&nbsp;6</a>, que iguala el salario real al producto marginal del trabajo.</p>
<pre class="text"><code>0 = -exp(a)*ALFA*exp(k)^(1-ALFA)*exp(n)^(ALFA-1) + exp(w);</code></pre>
</section>
</section>
<section id="ecuaciones-de-cierre-y-dinámica-agregada" class="level3">
<h3 class="anchored" data-anchor-id="ecuaciones-de-cierre-y-dinámica-agregada">Ecuaciones de Cierre y Dinámica Agregada</h3>
<p>Las últimas cuatro ecuaciones definen la tecnología, las identidades contables y la evolución de las variables de estado.</p>
<section id="ecuación-6-restricción-de-recursos" class="level5">
<h5 class="anchored" data-anchor-id="ecuación-6-restricción-de-recursos">Ecuación 6: Restricción de Recursos</h5>
<p>Corresponde a la Ecuación Matemática <a href="#eq-resource" class="quarto-xref">Ecuación&nbsp;7</a>.</p>
<pre class="text"><code>0 = -exp(c) - exp(iv) + exp(y);</code></pre>
</section>
<section id="ecuación-7-función-de-producción" class="level5">
<h5 class="anchored" data-anchor-id="ecuación-7-función-de-producción">Ecuación 7: Función de Producción</h5>
<p>Corresponde a la Ecuación Matemática <a href="#eq-prod-func" class="quarto-xref">Ecuación&nbsp;4</a>.</p>
<pre class="text"><code>0 = -exp(y) + exp(a)*exp(k)^(1-ALFA)*exp(n)^(ALFA);</code></pre>
</section>
<section id="ecuación-8-acumulación-de-capital" class="level5">
<h5 class="anchored" data-anchor-id="ecuación-8-acumulación-de-capital">Ecuación 8: Acumulación de Capital</h5>
<p>Corresponde a la Ecuación Matemática <a href="#eq-capital-accum" class="quarto-xref">Ecuación&nbsp;8</a>.</p>
<pre class="text"><code>0 = -exp(k(+1)) + (1-DELTA)*exp(k) + exp(iv);</code></pre>
</section>
<section id="ecuación-9-proceso-de-productividad" class="level5">
<h5 class="anchored" data-anchor-id="ecuación-9-proceso-de-productividad">Ecuación 9: Proceso de Productividad</h5>
<p>Corresponde a la Ecuación Matemática <a href="#eq-tech-proc" class="quarto-xref">Ecuación&nbsp;9</a>.</p>
<pre class="text"><code>0 = -log(exp(a)) + RHOA*log(exp(a(-1))) + u_a;</code></pre>
<pre class="text"><code>end;</code></pre>
</section>
</section>
</section>
<section id="el-bloque-steady_state_model-cálculo-del-equilibrio-a-largo-plazo" class="level2">
<h2 class="anchored" data-anchor-id="el-bloque-steady_state_model-cálculo-del-equilibrio-a-largo-plazo">El Bloque <code>steady_state_model</code>: Cálculo del Equilibrio a Largo Plazo</h2>
<p>Aquí describimos el bloque <code>steady_state_model</code>. Este bloque es una guía que le proporcionamos a Dynare para que pueda calcular el equilibrio a largo plazo de la economía de forma analítica, lo cual es mucho más eficiente y preciso que dejar que un algoritmo numérico lo intente por sí solo. Antes de analizar las fluctuaciones del modelo, Dynare debe encontrar su punto de equilibrio a largo plazo o estado estacionario. El bloque <code>steady_state_model</code> le proporciona una receta analítica para calcular estos valores de forma secuencial y eficiente.</p>
<pre class="text"><code>steady_state_model;

% 1. Se normaliza la tecnología y se calculan los precios de los factores
%    que solo dependen de parámetros.
A = 1;
RK = 1/BETTA - (1-DELTA); % Derivado de la Ecuación de Euler del Capital

% 2. Se calculan los ratios clave de la economía (respecto al trabajo, N)
%    en función de los precios ya conocidos.
K_O_N = (RK/(A*(1-ALFA)))^(-1/ALFA); % Ratio K/N, de la demanda de capital
W = A*ALFA*(K_O_N)^(1-ALFA);         % Salario, de la demanda de trabajo
IV_O_N = DELTA*K_O_N;                % Ratio I/N, de la ley de acum. de K
Y_O_N = A*K_O_N^(1-ALFA);            % Ratio Y/N, de la func. de producción
C_O_N = Y_O_N - IV_O_N;                % Ratio C/N, de la restricción de recursos

% 3. Se resuelve numéricamente para el nivel de trabajo (N).
%    Debido a la complejidad del problema del hogar, N no tiene una
%    solución analítica simple, por lo que se llama a una función externa.
[N, info]=RBC_MoM_steady_helper(THETA,ETAl,ETAc,BETTA,B,C_O_N,W);

% 4. Con el valor de N, se calculan los niveles absolutos de las demás variables.
C=C_O_N*N;
Y=Y_O_N*N;
IV=IV_O_N*N;
K=K_O_N*N;
LA = (C-B*C)^(-ETAc)-BETTA*B*(C-B*C)^(-ETAc); % Lambda, de la CPO del consumo

% 5. Se asigna el logaritmo de los valores de estado estacionario calculados
%    a las variables del modelo que Dynare utilizará para la solución dinámica.
k=log(K);
c=log(C);
a=log(A);
iv=log(IV);
y=log(Y);
la=log(LA);
n=log(N);
rk=log(RK);
w=log(W);

end;</code></pre>
<p>La lógica de este bloque es resolver el sistema de forma secuencial: primero calcula las variables que no dependen de otras (como la tasa de interés), luego los ratios que dependen de esas variables, y así sucesivamente hasta que solo queda una incógnita (el nivel de trabajo, <span class="math inline">\(N\)</span>), que se resuelve numéricamente. Con <span class="math inline">\(N\)</span> conocido, se pueden encontrar los niveles absolutos de todas las demás variables.</p>
</section>
</section>
<section id="estimación-por-método-de-momentos-simulado-smm" class="level1">
<h1>Estimación por Método de Momentos Simulado (SMM)</h1>
<p>Una vez especificado y calibrado el modelo, el siguiente paso es estimar un subconjunto de sus parámetros para mejorar el ajuste del modelo a los datos empíricos. Para ello, se utiliza el Método de Momentos Simulado (SMM). Esta sección detalla la configuración de dicho procedimiento en Dynare.</p>
<section id="parámetros-a-estimar" class="level2">
<h2 class="anchored" data-anchor-id="parámetros-a-estimar">Parámetros a Estimar</h2>
<p>El bloque <code>estimated_params</code> declara los parámetros que serán estimados. Los valores proporcionados sirven como punto de partida para el algoritmo de minimización. En este caso, se estiman siete parámetros clave que definen las preferencias de los hogares, la tecnología y el proceso estocástico.</p>
<pre class="text"><code>estimated_params;
  DELTA,    0.025;      // Tasa de depreciación ($\delta$)
  BETTA,    0.984;      // Factor de descuento ($\beta$)
  B,        0.5;        // Parámetro de hábitos de consumo (B)
  ETAc,     2;          // Parámetro de aversión al riesgo ($\eta_{c}$)
  ALFA,     0.667;      // Participación del trabajo en el producto ($\alpha$)
  RHOA,     0.979;      // Persistencia del shock de productividad ($\rhoa_{a}$)
  stderr u_a, 0.0072;   // Desviación estándar del shock ($\sigma_e$)
end;

estimated_params_init(use_calibration);
end;</code></pre>
</section>
<section id="momentos-a-igualar" class="level2">
<h2 class="anchored" data-anchor-id="momentos-a-igualar">Momentos a Igualar</h2>
<p>El núcleo del método consiste en minimizar la distancia entre un conjunto de momentos calculados a partir de los datos reales y los mismos momentos calculados a partir de datos simulados por el modelo.</p>
<p>El comando <code>varobs</code> vincula las variables del modelo con las series del archivo de datos. El bloque <code>matched_moments</code> especifica el conjunto de 18 momentos (medias, varianzas, covarianzas y autocovarianzas) que se utilizarán como criterio de ajuste.</p>
<pre class="text"><code>% Vincula variables del modelo a los datos
varobs c iv n;

% Define los 18 momentos a igualar
matched_moments;
c; %primeros momentos (las medias de las variables:  media del consumo 
n; % media de la inversión
iv; % media del trabajo
c*c; % Estos son los segundos momentos: varianza del consumo 
c*iv; % Covarianza entre variables
iv*n; % Covarianza entre variables
iv*iv; % Estos son los segundos momentos: varianza de la inversión 
n*c; Covarianza entre variables
n*n; % Estos son los segundos momentos: varianza del trabajo
c*c(-1); %Autocovarianzas de primer orden (consumo)
n*n(-1); %Autocovarianzas de primer orden (trabajo)
iv*iv(-1); %Autocovarianzas de primer orden (inversión)

c*c(-3); % autocovarianza de orden superior (consumo) de largo plazo
n*n(-3); % autocovarianza de orden superior (trabajo) de largo plazo
iv*iv(-3); % autocovarianza de orden superior (inversión) de largo plazo

c*c(-5); % autocovarianza de orden superior (consumo) de largo plazo
n*n(-5); % autocovarianza de orden superior (trabajo) de largo plazo
iv*iv(-5); % autocovarianza de orden superior (inversión) de largo plazo
end; % En total se esta pidiendo igualar 18 momentos </code></pre>
<p>##Configuración del Proceso de Estimación</p>
<p>El comando <code>method_of_moments</code> es el que ejecuta la estimación y agrupa todas las opciones que controlan el procedimiento.</p>
<pre class="text"><code>method_of_moments(
  // --- Opciones Fundamentales ---
  mom_method = SMM,                   // Método a usar: Método 
                                         de Momentos Simulado.
  datafile   = 'RBC_Data_2.mat',      // Nombre del archivo .mat 
                                         con los datos empíricos.

  // --- Opciones de Solución y Ponderación ---
  order = 2,                                   // Orden de la aproximación 
                                                  de Taylor para resolver 
                                            el modelo (lineal=1, cuadrático=2).
  weighting_matrix = ['DIAGONAL','OPTIMAL'],   // Especifica una estimación 
                                                en 2 etapas: primero con 
                                                una matriz diagonal y luego 
                                                con la matriz óptima.
  se_tolx=1e-6,                          // Tamaño de paso para el cálculo 
                                             numérico de errores estándar
  // --- Opciones Específicas de SMM ---
  simulation_multiple = 5,                // La longitud de la simulación 
                                            será 5 veces la longitud de 
                                           los datos reales para reducir 
                                            el error de simulación.

  // --- Opciones del Optimizador Numérico ---
  mode_compute = 4,                   // Especifica el algoritmo numérico 
                                         para encontrar el mínimo 
                                         de la función objetivo.
  additional_optimizer_steps = [13],    // Ejecuta otro algoritmo después 
                                           del primero para refinar 
                                           la búsqueda del mínimo.
  optim = ('TolFun'      , 1D-6,       // Tolerancia para la convergencia 
                                         del valor de la función objetivo.
           'TolX'        , 1e-6),      // Tolerancia para la convergencia 
                                         de los valores de los parámetros.

  // --- Opciones de Salida y Diagnóstico ---
  TeX,                                     // Genera tablas de resultados 
                                            en formato TeX para una fácil 
                                        inclusión en documentos académicos.
  mode_check                              // Crea gráficos para verificar
                                           visualmente que se ha encontrado 
                                           un mínimo para cada parámetro.
);</code></pre>
<p>La configuración del estimador se puede resumir en los siguientes puntos clave:</p>
<ul>
<li><strong>Método:</strong> Se utiliza el Método de Momentos Simulado (<code>SMM</code>).</li>
<li><strong>Datos:</strong> Los momentos empíricos se calculan a partir del archivo <code>RBC_Data_2.mat</code>.</li>
<li><strong>Solución del Modelo:</strong> El modelo se resuelve usando una aproximación de segundo orden (<code>order = 2</code>), lo que permite capturar efectos no lineales y de la incertidumbre.</li>
<li><strong>Ponderación:</strong> Se realiza una estimación en dos etapas. La primera utiliza una matriz de ponderación diagonal para obtener una estimación inicial. La segunda utiliza esta estimación para construir una matriz de ponderación óptima y obtener los resultados finales más eficientes.</li>
<li><strong>Simulación:</strong> Para cada evaluación de la función objetivo, el modelo se simula por un período 5 veces más largo que la muestra de datos para obtener una estimación precisa de los momentos teóricos.</li>
<li><strong>Optimización:</strong> Se utilizan los algoritmos numéricos 4 y 13 de Dynare para encontrar el mínimo de la función objetivo, con tolerancias de convergencia estrictas.</li>
<li><strong>Salida:</strong> Se solicita la generación de tablas en formato <code>TeX</code> y gráficos de diagnóstico (<code>mode_check</code>) para verificar la correcta convergencia del optimizador.</li>
</ul>
<p>#Resultados de la Estimación y Evaluación del Modelo</p>
<p>En esta sección se presentan y analizan los resultados obtenidos tras ejecutar el script de estimación por el Método de Momentos Simulado (SMM) en Dynare. La interpretación se centra en tres áreas clave: los valores de los parámetros estructurales estimados, la prueba de validez estadística del modelo en su conjunto y el ajuste específico momento por momento.</p>
</section>
<section id="parámetros-estructurales-estimados" class="level2">
<h2 class="anchored" data-anchor-id="parámetros-estructurales-estimados">Parámetros Estructurales Estimados</h2>
<p>Tras el proceso de minimización en dos etapas, Dynare reporta las estimaciones puntuales de los parámetros, junto con medidas de su precisión estadística. La tabla de resultados principal es la siguiente:</p>
<pre class="text"><code>RESULTS FROM SMM ESTIMATION
parameters
        Estimate     s.d.     t-stat
DELTA     0.0238   0.0011    21.3869 
BETTA     0.9854   0.0012   812.9821 
B         0.4945   0.0032   154.5105 
ETAc      2.0044   0.0034   594.0101 
ALFA      0.6729   0.0047   141.8335 
RHOA      0.9807   0.0020   500.0623 

standard deviation of shocks
        Estimate      s.d.    t-stat
u_a       0.0070    0.0002   37.5090 </code></pre>
<p>La interpretación de esta tabla es la siguiente:</p>
<ul>
<li><p><strong>Estimate (Estimación):</strong> Son los valores de los parámetros (<span class="math inline">\(\hat{\theta}\)</span>) que mejor permiten al modelo replicar los momentos de los datos. Por ejemplo, el factor de descuento (<span class="math inline">\(\beta\)</span>) se estima en 0.9854, sugiriendo que los hogares son relativamente pacientes. La tasa de depreciación (<span class="math inline">\(\delta\)</span>) se estima en 0.0238, lo que implica una depreciación anual de aproximadamente 9.5%.</p></li>
<li><p><strong>s.d. (Desviación Estándar):</strong> Mide la incertidumbre o precisión de cada estimación. Valores pequeños, como los obtenidos, indican que los parámetros están estimados con alta precisión.</p></li>
<li><p><strong>t-stat (Estadístico t):</strong> Prueba la hipótesis nula de que el parámetro es igual a cero. Valores absolutos muy superiores a 2, como los que se observan en todos los casos, nos permiten rechazar contundentemente esa hipótesis, confirmando que todos los parámetros son estadísticamente significativos.</p></li>
</ul>
</section>
<section id="prueba-de-especificación-del-modelo-prueba-j" class="level2">
<h2 class="anchored" data-anchor-id="prueba-de-especificación-del-modelo-prueba-j">Prueba de Especificación del Modelo (Prueba J)</h2>
<p>Más allá de los valores individuales de los parámetros, el SMM nos proporciona una prueba formal para la validez general del modelo, conocida como la prueba J de sobreidentificación de Hansen.</p>
<pre class="text"><code>Value of J-test statistic: 2.580075
p-value of J-test statistic: 0.995194</code></pre>
<p>La prueba J evalúa la hipótesis nula (<span class="math inline">\(H_0\)</span>) de que el modelo está correctamente especificado, es decir, que las desviaciones entre los momentos teóricos y empíricos son, en conjunto, estadísticamente iguales a cero.</p>
<p>En nuestro caso, se igualaron <span class="math inline">\(k=18\)</span> momentos y se estimaron <span class="math inline">\(p=7\)</span> parámetros. Por lo tanto, la J-statistic sigue una distribución Chi-cuadrado (<span class="math inline">\(\chi^2\)</span>) con <span class="math inline">\(k-p = 11\)</span> grados de libertad.</p>
<p>El valor de la J-statistic obtenida es de 2.58. El <code>p-value</code> asociado es de 0.995 (o 99.5%). Dado que este p-value es muy superior a los niveles de significancia convencionales (e.g., 5% o 10%), no se puede rechazar la hipótesis nula. La conclusión es que el modelo, según los 18 momentos seleccionados, es una representación estadísticamente válida y un buen ajuste a los datos.</p>
</section>
<section id="análisis-del-ajuste-de-los-momentos" class="level2">
<h2 class="anchored" data-anchor-id="análisis-del-ajuste-de-los-momentos">Análisis del Ajuste de los Momentos</h2>
<p>Finalmente, la salida nos permite inspeccionar el ajuste del modelo momento por momento, cuantificando el éxito del proceso de minimización.</p>
<div id="tbl-comparison_moments_SMM" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-comparison_moments_SMM-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;1: Comparación de los momentos de datos coincidentes y los momentos del modelo (SMM)
</figcaption>
<div aria-describedby="tbl-comparison_moments_SMM-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 65%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Moment</th>
<th style="text-align: center;">Data</th>
<th style="text-align: center;">Model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(E \left[ {C}_{t} \right]\)</span></td>
<td style="text-align: center;">-0.1850290</td>
<td style="text-align: center;">-0.1854001</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(E \left[ {N}_{t} \right]\)</span></td>
<td style="text-align: center;">-0.9948910</td>
<td style="text-align: center;">-0.9946098</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(E \left[ {I}_{t} \right]\)</span></td>
<td style="text-align: center;">-1.5650115</td>
<td style="text-align: center;">-1.5649857</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(E \left[ {C}_{t} \times {C}_{t} \right]\)</span></td>
<td style="text-align: center;">0.0351482</td>
<td style="text-align: center;">0.0352509</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(E \left[ {I}_{t} \times {I}_{t} \right]\)</span></td>
<td style="text-align: center;">2.4560278</td>
<td style="text-align: center;">2.4561806</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(E \left[ {N}_{t} \times {N}_{t} \right]\)</span></td>
<td style="text-align: center;">0.9900779</td>
<td style="text-align: center;">0.9895088</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(E \left[ {C}_{t} \times {I}_{t} \right]\)</span></td>
<td style="text-align: center;">0.2914192</td>
<td style="text-align: center;">0.2919621</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(E \left[ {N}_{t} \times {I}_{t} \right]\)</span></td>
<td style="text-align: center;">1.5563575</td>
<td style="text-align: center;">1.5559421</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(E \left[ {C}_{t} \times {N}_{t} \right]\)</span></td>
<td style="text-align: center;">0.1836161</td>
<td style="text-align: center;">0.1839545</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(E \left[ {C}_{t} \times {C}_{t-1} \right]\)</span></td>
<td style="text-align: center;">0.0351451</td>
<td style="text-align: center;">0.0352500</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(E \left[ {N}_{t} \times {N}_{t-1} \right]\)</span></td>
<td style="text-align: center;">0.9900741</td>
<td style="text-align: center;">0.9895016</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(E \left[ {I}_{t} \times {I}_{t-1} \right]\)</span></td>
<td style="text-align: center;">2.4554081</td>
<td style="text-align: center;">2.4557268</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(E \left[ {C}_{t} \times {C}_{t-3} \right]\)</span></td>
<td style="text-align: center;">0.0351327</td>
<td style="text-align: center;">0.0352409</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(E \left[ {N}_{t} \times {N}_{t-3} \right]\)</span></td>
<td style="text-align: center;">0.9900639</td>
<td style="text-align: center;">0.9894868</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(E \left[ {I}_{t} \times {I}_{t-3} \right]\)</span></td>
<td style="text-align: center;">2.4544564</td>
<td style="text-align: center;">2.4550471</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(E \left[ {C}_{t} \times {C}_{t-5} \right]\)</span></td>
<td style="text-align: center;">0.0351159</td>
<td style="text-align: center;">0.0352267</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(E \left[ {N}_{t} \times {N}_{t-5} \right]\)</span></td>
<td style="text-align: center;">0.9900501</td>
<td style="text-align: center;">0.9894720</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(E \left[ {I}_{t} \times {I}_{t-5} \right]\)</span></td>
<td style="text-align: center;">2.4537771</td>
<td style="text-align: center;">2.4544787</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>La tabla muestra que los valores de la columna Data (momentos empíricos, <span class="math inline">\(\hat{m}\)</span>) y la columna Model (momentos teóricos evaluados en <span class="math inline">\(\hat{\theta}\)</span>, <span class="math inline">\(m(\hat{\theta})\)</span>) son extremadamente cercanos. Por ejemplo, la media del consumo es -0.1850 en los datos y -0.1854 en el modelo. Este excelente ajuste a nivel individual es consistente con el resultado favorable de la prueba <span class="math inline">\(J\)</span>.</p>



</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/yuberley20\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026, Yuberley Cruz Caycedo</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Construido con <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>